### ISSUE TITLE
Merging tabs has unexpected behaivior

### ISSUE THREAD

**Issue by MTschannett** [negativo/BettermarksIssues#1]
When i press the merge button, all open tabs get doubled.
If I press the save button, only the tabs which are really open at that moment get saved. 

Tabs after pressing a few times merge:
![merged tabs](https://cloud.githubusercontent.com/assets/18646672/26327398/9856a4dc-3f3f-11e7-9acb-36a8b2cbe030.PNG)

Tabs after re saving tabs:
![re-saved](https://cloud.githubusercontent.com/assets/18646672/26327399/98664aae-3f3f-11e7-87d7-757e1159599c.PNG)

I think the right behaivior would be to gather all tabs from all open chrome instances.

**Comment by negativo** [comment]
@MTschannett thanks
will add a filter to avoid saving the urls that you already have

**Comment by negativo** [comment]
fixed + new awesome features in the next release. should have some time to release it this weekend.
cheers
